global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
